### ISSUE TITLE
Add Configuration Menu and View

### ISSUE THREAD

**Issue by Citrullin** [KaiOS-Nano-wallet/nano-kaios#10]

**Comment by mehlium** [comment]
Started thinking a bit about user flow on #8, and soon we need to structure this a bit more going forward. What about something like:

* Wallet (top view, Setup is show if no wallet has been set up)
    * accounts (list of account / alias / balance), and when selecting account:
        * transactions
        * send
         * receive
         * configure (change alias, hide etc)
    * add account
* Configure (reachable with "menu" button)
* About (reachable with "menu" button)

An alternative approach would be to always show all accounts under for instance send/receive/transactions :thinking:

**Comment by Citrullin** [comment]
I had to think about this for a minute. There also needs to be an additional update after selecting the account. The account is not automatically updated, since the user is not online the whole time. Additionally to updating it by hand, I would also say that we update it, of course, when the user sends a tx. Btw: Does the user need to be online in order to generate a QR code?

To summarize it:

* Wallet (top view, Setup is show if no wallet has been set up)
    * accounts (list of account / alias / balance / add account button), and when selecting account:
        * Update
        * transaction history
        * send
         * receive
         * configure (change alias, hide etc)
    * add account
* Configure (reachable with "menu" button)
* About (reachable with "menu" button)

I would also add Receive and Send to the menu. This makes it redundant, but reduces user confusion. Some might take that route and we got enough space for this, I think.

**Comment by mehlium** [comment]
Agree, having send/receive available in the main menu sounds smart. We could even show it as "send / receive" for a given account.  No, not necessary to be online for generating QR code (implemented in #20).

**Comment by Citrullin** [comment]
Okay, so, I think we shouldn't force the user to go online then. But after generating the QR Code, we should give the option to update the wallet with the generated QR code.

**Comment by mehlium** [comment]
Yes, that could even be a settings thing? Eagerly load balance / transactions, or only load when requested in the UI.

**Comment by Citrullin** [comment]
> Yes, that could even be a settings thing? Eagerly load balance / transactions, or only load when requested in the UI.

Love that

**Comment by mehlium** [comment]
Accidentally closed this one, re-opened for more UI talk.

**Comment by rtaibah** [comment]
Hi there! Here is a quick and rough start.

## Home screen
List all the accounts and add an account here. Also general app config can be accessed at the top (we can add the about section inside here too!)

![home](https://user-images.githubusercontent.com/707668/100754717-743f1b00-33fc-11eb-82f4-4e4b2b605a41.png)

## Account Pages

Here a user can manage the account. A back button in the header to go to home.

### Account Transactions

List all the transaction history and a refresh button at the top.

![image](https://user-images.githubusercontent.com/707668/100755764-95543b80-33fd-11eb-9a44-4009d0d60db3.png)

### Send Page

Users can send Nano from this page. Some UX considerations include a paste address button and QR scanning button.

![image](https://user-images.githubusercontent.com/707668/100755734-8d949700-33fd-11eb-992c-a0672508a85d.png)

### Receive Page

![account-recieve](https://user-images.githubusercontent.com/707668/100754707-72755780-33fc-11eb-98d0-e9c7a4772c66.png)

### Account Configuration Page

![account-configure](https://user-images.githubusercontent.com/707668/100754701-70ab9400-33fc-11eb-8c57-fdc8d38f3be8.png)

**Comment by Citrullin** [comment]
@rtaibah This looks nice, but it doesn't follow the KaiOS UI. Since we want to get it into the KaiOS store, we have to follow their UI rules.
https://developer.kaiostech.com/design-guide/ui-component

**Comment by rtaibah** [comment]
This is based of a UI kit I downloaded for KaiOS. I just change the colors.

**Comment by Citrullin** [comment]
> 
> 
> This is based of a UI kit I downloaded for KaiOS. I just change the colors.

Can you post a link? I see a lot of elements which violate their rulings. Check the page I posted. They have clear rulings where and how to use specific elements. The soft bottoms are only three buttons and it looks completely different. The separator is too high and cannot have a dark blue color. I know this ruling is a big restrictive, but we need an UI we can submit to the store. They probably don't make an exception for a wallet app. The only exceptions I've seen so far are for games. And it makes sense there. I want to get this app into the store, this is why I don't want to risk anything with the UI, even if it would look better.

**Comment by rtaibah** [comment]
Here it is. Granted it's a year old.

https://sketchelements.com/kaios-ui-kit/

But if they are very strict about these things, I'll spend more time understanding the platform. Sorry I rushed in I guess. 

I'll start here https://medium.com/design-at-kai

UPDATE: That said, the above screens have value as wireframes. Any feedback on how everything is laid out?

**Comment by Citrullin** [comment]
> 
> 
> Here it is. Granted it's a year old.
> 
> https://sketchelements.com/kaios-ui-kit/
> 
> But if they are very strict about these things, I'll spend more time understanding the platform. Sorry I rushed in I guess.
> 
> I'll start here https://medium.com/design-at-kai
> 
> UPDATE: That said, the above screens have value as wireframes. Any feedback on how everything is laid out?

Sorry, if I sound to harsh, but they don't. We cannot use them, because they don't work with the design of the phone and how navigation works on the phone. There are some ideas I like though. For example shorting the address in accounts. That is something we didn't thought about and that makes sense.

**Comment by rtaibah** [comment]
No problem. My bad I made assumptions they work like smartphones.

**Comment by Citrullin** [comment]
> 
> 
> No problem. My bad I made assumptions they work like smartphones.

Do you want to have a call? I can show you one phone in real life and some apps for it. :)

**Comment by mehlium** [comment]
@rtaibah Wow, first of all great job :clap: Yeah, there are some strict guidelines for this platform, and especially the "physical keys" mapping to the "menu" at the bottom (where a device has three buttons). I really like the color scheme, and hope that we can go in that direction while also complying with the guidelines. I also like the icons for the menu, and is something we could bake into the pop-up menu.

**Comment by mehlium** [comment]
@rtaibah @Citrullin 
![Peek 2021-01-05 21-18](https://user-images.githubusercontent.com/788059/103694652-9c8ddc80-4f9b-11eb-81e1-fc60a937f812.gif)

Are latest UI changes OK for V1? ↑

**Comment by mehlium** [comment]
Closes this one and will open new UI issues on request.
