### ISSUE TITLE
Address gone when transaction fails

### ISSUE THREAD

**Issue by Citrullin** [KaiOS-Nano-wallet/nano-kaios#105]
When a user scans a QR code, tries to send the transaction, but it fails, the nano address is gone and the user has to go back again and needs to scan the QR code again.

**Comment by mehlium** [comment]
This is kind of challenging to solve without keeping the state of the inputted address somewhere. I think this should go into improvements after V1 :thinking:

**Comment by Citrullin** [comment]
It's a minor issue, so that should be fine.
