### ISSUE TITLE
Add ESLint

### ISSUE THREAD

**Issue by Citrullin** [KaiOS-Nano-wallet/nano-kaios#13]
I just recognized that I use `{ name }` while you use `{name}`. 
I am not strongly opinionated on this. But I guess it makes sense to have a common style rules on that. So, adding ESLint makes sense, I guess.

**Comment by mehlium** [comment]
Totally agree on this! Same for me what style we chose, as long as we have the same!

**Comment by Citrullin** [comment]
Just copy some ESLint and pollup config from some project you have on hand. :D
