### ISSUE TITLE
Download localizations

### ISSUE THREAD

**Issue by Citrullin** [KaiOS-Nano-wallet/nano-kaios#16]
In order to reduce the size of the app localization needs to get downloaded dynamically. Find and implement a way how to handle this mechanism. When the user opens the app for the first time, it should download the required localization and caches it. When the user is offline there needs to be an error message with the information that there is the need to get connected to the Internet, in order to download the localization file.

**Comment by mehlium** [comment]
Given the complexity of this, and how small the size of the localisations are, we can close this.
