### ISSUE TITLE
Push menu to history

### ISSUE THREAD

**Issue by Citrullin** [KaiOS-Nano-wallet/nano-kaios#24]
When the user selects the menu, it doesn't get pushed to the history. Therefore, the user is not able to return back after they selected something in the menu. The menu should be included in the history.

**Comment by mehlium** [comment]
I have a few thoughts on how to fix this properly, and also reduce the amount of stores we need. Essentially having a state interface, filled out as the user navigates. This should remove the need for a "back"-action (which is kind of broken at the moment).

**Comment by mehlium** [comment]
Closed with merge.
