### ISSUE TITLE
Fix scrolling to update

### ISSUE THREAD

**Issue by Citrullin** [KaiOS-Nano-wallet/nano-kaios#44]
When scrolling to update, the button isn't visible. Fix it.

**Comment by mehlium** [comment]
I think it makes sense to have this as the "left bottom button" in KaiOS? In `Wallet` view left button could be "add account", and in `Account`-view left button could be "update". What do you think @Citrullin?

**Comment by Citrullin** [comment]
> 
> 
> I think it makes sense to have this as the "left bottom button" in KaiOS? In `Wallet` view left button could be "add account", and in `Account`-view left button could be "update". What do you think @Citrullin?

Yes, sounds fine to me. Eventually I hope we get a more finished UI by @rtaibah, which takes all of these issues into account.

**Comment by mehlium** [comment]
Closes this now as it's not relevant any longer.
