### ISSUE TITLE
Receiving 0.000001 shows 0.00000

### ISSUE THREAD

**Issue by Citrullin** [KaiOS-Nano-wallet/nano-kaios#82]
Just a minor issue. The minimum amount you can send in Natrium is 0.000001.
When sending this to the KaiOS wallet, it just show 0. Maybe we should make it dynamic. So, that the sub 1 adapts to the highest depth ever received/send.

**Comment by mehlium** [comment]
Good catch, a max depth is kind of tricky UI wise though (there can be a lot of zeroes). We could show for instance: `0.0000..` to indicate that there is some amout there more than `0`, but we never care to show it in the header.

**Comment by Citrullin** [comment]
> 
> 
> Good catch, a max depth is kind of tricky UI wise though (there can be a lot of zeroes). We could show for instance: `0.0000..` to indicate that there is some amout there more than `0`, but we never care to show it in the header.

Fair enough, should we maybe just adapt to 6 places, because that is the maximum depth in Natrium as well? But having it dynamically adapt? So, when I only received 1.25, it shows 1.25 and not 1.250000

**Comment by mehlium** [comment]
Yeah, that sounds like a good change :+1:
