### ISSUE TITLE
Support both regular Nano Seed and BIP39 seed?

### ISSUE THREAD

**Issue by mehlium** [KaiOS-Nano-wallet/nano-kaios#93]
The current implementation only supports BIP39 through the https://www.npmjs.com/package/nanocurrency-web library. This makes it so we can't import regular nano seeds (as with https://github.com/marvinroger/nanocurrency-js for instance). We could probably go live with BIP39 only, but should perhaps go live with regular first? :thinking: Related to #77

**Comment by Citrullin** [comment]
Yes, BIP39 is fine. A bit long, but fine.
